version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn config.wsgi.application -w 4 -b 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  postgres_data:
