# Generated by Django 5.0.3 on 2024-03-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('title',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
